# - Find mysqlclient
# Find the native MySQL includes and library
#
#  MARIADB_INCLUDE_DIR - where to find mysql.h, etc.
#  MARIADB_LIBRARIES   - List of libraries when using MySQL.
#  MARIADB_FOUND       - True if MySQL found.

IF (MARIADB_INCLUDE_DIR)
  # Already in cache, be silent
  SET(MARIADB_FIND_QUIETLY TRUE)
ENDIF (MARIADB_INCLUDE_DIR)

IF (DEFINED ENV{MARIADB_DIR})
  set(MARIADB_DIR $ENV{MARIADB_DIR})
ENDIF()

FIND_PATH(MARIADB_INCLUDE_DIR mariadb/mysql.h
  /usr/local/include
  /usr/include
  ${MARIADB_DIR}/include
)

SET(MARIADB_NAMES mariadb libmariadbclient)
FIND_LIBRARY(MARIADB_LIBRARY
  NAMES ${MARIADB_NAMES}
  PATHS /usr/lib /usr/local/lib ${MARIADB_DIR}/lib
  PATH_SUFFIXES mariadb
)

IF (MARIADB_INCLUDE_DIR AND MARIADB_LIBRARY)
  SET(MARIADB_FOUND TRUE)
  SET( MARIADB_LIBRARIES ${MARIADB_LIBRARY} )
ELSE (MARIADB_INCLUDE_DIR AND MARIADB_LIBRARY)
  SET(MARIADB_FOUND FALSE)
  SET( MARIADB_LIBRARIES )
ENDIF (MARIADB_INCLUDE_DIR AND MARIADB_LIBRARY)

IF (MARIADB_FOUND)
  IF (NOT MARIADB_FIND_QUIETLY)
    MESSAGE(STATUS "Found MySQL: ${MARIADB_LIBRARY}")
  ENDIF (NOT MARIADB_FIND_QUIETLY)
ELSE (MARIADB_FOUND)
  IF (MARIADB_FIND_REQUIRED)
    MESSAGE(STATUS "Looked for MySQL libraries named ${MARIADB_NAMES}.")
    MESSAGE(FATAL_ERROR "Could NOT find MySQL library")
  ENDIF (MARIADB_FIND_REQUIRED)
ENDIF (MARIADB_FOUND)

MARK_AS_ADVANCED(
  MARIADB_LIBRARY
  MARIADB_INCLUDE_DIR
  )
